### PR TITLE
feat: added  data model for library and faculty

### PR DESCRIPTION
**Pull request by piyush-json**
for #16 
Added data models for library and faculty.

### CODE REVIEW

**Comment by piyush-json** [comment]
@shraddhapandeyy  if there are no issues please merge it

**Comment by shraddhapandeyy** [comment]
Good Work @piyush-panpaliya

**Comment by abhi887449** [comment]
@shraddhapandeyy you mention in issue #2 that we use mysql database then why using mongoose. Are we shifting from MySQL to MongoDB

**Comment by piyush-json** [comment]
I also had same doubt when I saw package.json after cloning locally, but when I opened the issue and specifically told mongodb but it was go ahead so I continued.

**Pull request merged**
